### ISSUE TITLE
`sc install` failed on macOS

### ISSUE THREAD

**Issue by maqiuyujoyce** [GoogleCloudPlatform/k8s-service-catalog#106]
`sc install` failed with the following reason even if `sc check` succeeded:

> Service Catalog could not be installed
> Error: error generating YAML files: error generating SSL artifacts : error generating ca: stdout:  stderr: 

cfssl tools seem to be the root cause. Ran `./cfssl` under $GOPATH/bin and got:

> Killed: 9

**OS:** macOS High Sierra Version 10.13.2
**Workaround:** Under $GOPATH/bin, do `rm cfssl*`, and install cfssl tools manually: `go install -ldflags -s github.com/cloudflare/cfssl/cmd/...`.
**Note:** After I ran the workaround for the first time, `./cfssl` worked but `sc install` still failed. Then I did the workaround again, and this time `sc install` succeeded. Not sure what happened.

I don't know why this issue happens, and whether the issue and workaround are reproducible. But for the convenience of future users, we might want to fix it.

**Comment by martinmaly** [comment]
Possibly duplicate of #111

**Comment by mihnjong** [comment]
Do we run "base64 -d" in sc? If so, we should change it to "base64 --decode".

**Comment by maqiuyujoyce** [comment]
No `base64 -d` isn't called in sc installer.

**Comment by maqiuyujoyce** [comment]
Solution is #111
