### ISSUE TITLE
Have "sc check" print default `gcloud` settings including `project` and `zone`

### ISSUE THREAD

**Issue by mihnjong** [GoogleCloudPlatform/k8s-service-catalog#113]
"sc install" implicitly uses `gcloud` config including `project` and `zone`. It would be better if "sc check" explicitly shows the gcloud configuration that will be used.

We can get the configuration via `gcloud config list`. I think we can print "account" (GCP user email) as well.

**Comment by maqiuyujoyce** [comment]
I am curious - what's the problem of not showing the config properties? 
New GKE users will go through the steps, which include how to setup/verify the configs. And sophisticated GKE users should have already known how to check the configs.
Also, when we create a new GCE vm (or running any other commands), gcloud won't notify us which zone and project it's going to use. So I figured we might want to follow this interaction pattern.
