### ISSUE TITLE
`gcloud components install beta` is required for `sc add-gcp-broker`

### ISSUE THREAD

**Issue by mihnjong** [GoogleCloudPlatform/k8s-service-catalog#117]
`sc check` should check if `gcloud beta` is ready. Also, `sc add-gcp-broker` print out the error message that`gcloud components install beta` is required if it's not installed yet.

**Comment by maqiuyujoyce** [comment]
The only `gcloud beta` commands used in sc installer are `gcloud beta iam`, and `gcloud iam` is v1 now (see #125). Seems unnecessary to do the check any more.

**Comment by maqiuyujoyce** [comment]
Based on #125, we no longer need `gcloud beta` component. Closing the issue.
