### ISSUE TITLE
Error enabling servicebroker.googleapis.com

### ISSUE THREAD

**Issue by mattfarina** [GoogleCloudPlatform/k8s-service-catalog#182]
I'm getting an error:

> enabling a GCP API: servicebroker.googleapis.com
> failed to configure GCP broker

I'm being directed to go to https://console.developers.google.com/apis/api/servicebroker.googleapis.com/overview?project=[MY-PROJECT] to enable it. But, on that site I get the error:

>  The API "servicebroker.googleapis.com" doesn't exist or you don't have permission to access it 

I am an owner on that project. How should I proceed to try the service broker?

**Comment by martinmaly** [comment]
Hi,

apologies for the delayed response. the broker is now accessible. Here is the public announcement:
https://cloudplatform.googleblog.com/2018/04/Introducing-Kubernetes-Catalog-and-GCP-Open-Service-Broker.html

Cheers
Martin
