### ISSUE TITLE
failed install followed by uninstall doesn't unblock installation

### ISSUE THREAD

**Issue by bmelville** [GoogleCloudPlatform/k8s-service-catalog#28]
My installation failed because I had not granted cluster admin access to myself. Running install again caused this failure:

```
$ sc install
generated service catalog deployment config in dir: /tmp/service-catalog021394536 
Service Catalog could not be installed
error deploying YAML files: deploy failed with output: exit status 1 :Error from server (AlreadyExists): error when creating "/tmp/service-catalog021394536/namespace.yaml": namespaces "service-catalog" already exists
```

I tried `sc uninstall` but it didn't clean up the namespace. It would be great to either have

1. Uninstall clean up the namespace, or,
2. Install re-use the namespace if it exists.

**Comment by droot** [comment]
Thanks for reporting it. 
sc uninstall does clean up the namespace in current implementation. There is a caveat though, namespace deletion is async, so there will be delay in namespace deletion. So if you run `sc install` immediately after `sc uninstall`, it will fail.

We can probably have a wait for namespace deletion in the `sc uninstall` before declaring uninstallation successful.
