### ISSUE TITLE
integration test needs to verify resource create/delete successfully from deployment manager side

### ISSUE THREAD

**Issue by quanjielin** [GoogleCloudPlatform/k8s-service-catalog#33]
integration test needs to verify resource create/delete successfully from deployment manager side

currently when ./test/e2e.sh finished successful, from pantheon, binding deployment is deleted as expected, however instance deployment still there.

**Comment by quanjielin** [comment]
from logs, it's the timing issue which caused instance deployment failed be deleted. When test script asked GKE catalog to delete instance, deletebinding in broker side still hasn't finished yet, so broker failed to delete that instance deployment which had binding associated. 

The issue should be gone after we switching to status polling.

**Comment by mihnjong** [comment]
@quanjielin  Is this the dup of #34 ?
