### ISSUE TITLE
Add sc update command

### ISSUE THREAD

**Issue by droot** [GoogleCloudPlatform/k8s-service-catalog#36]
`sc` should support an update subcommand to address the following:

- upgrade service catalog components (apiserver/controller release updates)
- upgrade etcd version
- upgrade etcd-operator version
- upgrade auth manager version

So subcommand structure should be:

sc update <component-name> <component-specific-update-args>

Examples:
sc update service-catalog apimanager=gcr.io/apiserver:0.1.0 controllermanager=quay.io/controller-manager:0.1.0
sc update etcd version=0.2.0
sc update auth-manager ....

**Comment by droot** [comment]
cc @seans3

**Comment by martinmaly** [comment]
This seems to have been implemented (at least in basic form) by #37 
Further improvements to update command seem to be tracked by #105
