### ISSUE TITLE
Need to clean up service account json key in "remove-gcp-broker"

### ISSUE THREAD

**Issue by seans3** [GoogleCloudPlatform/k8s-service-catalog#38]
In the "add-gcp-broker" sub-command, a service account is created (if it doesn't already exist) and a JSON key for this service account is created and downloaded. Currently, we don't remove/delete this key from the service account when we call "remove-gcp-broker". Only about a dozen keys are allowed for a service account, so we eventually run out of keys for the service account and throw an error.

**Comment by quanjielin** [comment]
I hit same problem :)

quanlin@quanlin:~/dm/prototype/1021git/bin$ ./sc add-gcp-broker
using project:  quanlin-gke-e2e5
enabled required APIs  [deploymentmanager.googleapis.com servicebroker.googleapis.com serviceregistry.googleapis.com]
failed to configure GCP broker
error creating service account key :failed to create service account key:  : exit status 1

after removing some keys manually, it succeeded.
quanlin@quanlin:~/dm/prototype/1021git/bin$ ./sc add-gcp-broker
using project:  quanlin-gke-e2e5
enabled required APIs  [deploymentmanager.googleapis.com servicebroker.googleapis.com serviceregistry.googleapis.com]
generated the key at : /tmp/service-catalog-gcp562396553/key.json
GCP broker added successfully.

**Comment by mihnjong** [comment]
The solution for #120 will fix this issue.

**Comment by maqiuyujoyce** [comment]
If we keep running `sc add-gcp-broker`, we will get failures from the second time. However, the failure won't stop new keys from being created. So we may want to remove the newly created key when `sc add-gcp-broker` failed.
