### ISSUE TITLE
`sc add-gcp-broker` shows `exit status 1` error.

### ISSUE THREAD

**Issue by mihnjong** [GoogleCloudPlatform/k8s-service-catalog#62]
$ sc add-gcp-broker      
                     
```                                                                                                       
using project:  [MY_PROJECT_NAME]                                                                                                                   
enabled required APIs  [deploymentmanager.googleapis.com servicebroker.googleapis.com serviceregistry.googleapis.com]                                 
error fetching service account :failed to retrieve service account : exit status 1:generated the key at : /tmp/service-catalog-gcp903543596/key.json  
GCP broker added successfully.  
```      

Can we remove "exit status 1:" message? This is not a real error. The installer has a logic to create a service account when it does not exist.

**Comment by maqiuyujoyce** [comment]
CreateServiceAccount will be called if there is an error retrieving SA, and the error doesn't have to be a not_found error. (https://github.com/GoogleCloudPlatform/k8s-service-catalog/blob/master/installer/pkg/cmd/gcp_broker.go#L130)

So in addition to removing the "error fetching ..." message, we want to print out the error when CreateServiceAccount failed.

However, if the SA already exists, and for some reason, GetServiceAccount doesn't work properly, then CreateServiceAccount will always print out an error, which will confuse the customers. So we will eventually need to process the GetServiceAccount error based on the error code.

**Comment by maqiuyujoyce** [comment]
The left part is to distinguish between the not found error and other errors.

**Comment by maqiuyujoyce** [comment]
Now no error is printed if we can't retrieve the service account.
