### ISSUE TITLE
Introduce broker-cli tool

### ISSUE THREAD

**Issue by bmelville** [GoogleCloudPlatform/k8s-service-catalog#75]
The broker-cli tool allows for debugging and managing brokers from the Google Cloud Service Broker API. It uses the existing broker-cli library already existing as part of the installer.

Introduction of this tool will require the following steps:

- [x] Refactor existing broker-cli code out of installer into its own top-level directory
- [x] Vendor broker-cli library into installer to decouple
- [x] Remove old broker-cli from installer/pkg
- [x] Introduce recent changes/additions to the library to support the tool
- [x] Introduce the tool itself

**Comment by mihnjong** [comment]
@martinmaly @maqiuyujoyce 

Joyce found two copies of broker-cli code in the repo. Now, I see what Brendan was planning. Joyce, could you take it over ?

**Comment by mihnjong** [comment]
The next step is "Remove old broker-cli from installer/pkg"

**Comment by maqiuyujoyce** [comment]
broker-cli at the root and all the unused files under installer/pkg/broker-cli has been removed.
