### ISSUE TITLE
Auth Manager Binary should be hosted in gcp-services project in GCS

### ISSUE THREAD

**Issue by droot** [GoogleCloudPlatform/k8s-service-catalog#77]

**Comment by mihnjong** [comment]
@droot and @seans3 Could you give more decription about this issue? Where's the source code and the location of the binary as of now? And, what's the benefits of moving to gcp-services project?

Do you think it should be done before making a big announcement?

**Comment by mihnjong** [comment]
Auth manager code is at https://github.com/GoogleCloudPlatform/k8s-service-catalog/tree/master/catalog-oauth

We want to push the image to gcr.io/gcp-services or so.

**Comment by mihnjong** [comment]
Another TODO: update README.md to explain the release process of Auth Manger.

**Comment by martinmaly** [comment]
gcr.io/gcp-services/catalog-oauth:latest now exists. Updating installer to use it.

**Comment by martinmaly** [comment]
#138 has the fix.

**Comment by martinmaly** [comment]
#138 was merged. Closing
